language: node_js
node_js:
   - "10"
install:
  - npm install -g codecov
script:
  - NODE_ENV=test YOURPACKAGE_COVERAGE=1 ./node_modules/.bin/mocha \
  --require blanket \
  --reporter mocha-lcov-reporter
codecov