language: node_js
node_js:
  - "8"
  - "10"

jobs:
    include:
        node_js: node_js
        script: mocha --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage